apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB
              value: todo
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: p@ss123
            - name: MYSQL_USER
              value: todouser
          image: tnoone125/api-service:latest
          name: api-service
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
