apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /var/lib/mysql
  storageClassName: manual

