services:
  api-service:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: todouser
      MYSQL_PASSWORD: p@ss123
      MYSQL_DB: todo
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todouser
      MYSQL_PASSWORD: p@ss123
    volumes:
      - ./entries.sql:/docker-entrypoint-initdb.d/entries.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
